/* automatically generated by rust-bindgen 0.69.4 */

extern "C" {
    pub fn initAndResetChip() -> *mut ::core::ffi::c_void;
    pub fn destroyChip(state: *mut ::core::ffi::c_void);
    pub fn step(state: *mut ::core::ffi::c_void);
    pub fn chipStatus(state: *mut ::core::ffi::c_void);
    pub fn readPC(state: *mut ::core::ffi::c_void) -> ::core::ffi::c_ushort;
    pub fn readA(state: *mut ::core::ffi::c_void) -> ::core::ffi::c_uchar;
    pub fn readX(state: *mut ::core::ffi::c_void) -> ::core::ffi::c_uchar;
    pub fn readY(state: *mut ::core::ffi::c_void) -> ::core::ffi::c_uchar;
    pub fn readSP(state: *mut ::core::ffi::c_void) -> ::core::ffi::c_uchar;
    pub fn readP(state: *mut ::core::ffi::c_void) -> ::core::ffi::c_uchar;
    pub fn readRW(state: *mut ::core::ffi::c_void) -> ::core::ffi::c_uint;
    pub fn readAddressBus(
        state: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_ushort;
    pub fn writeDataBus(
        state: *mut ::core::ffi::c_void,
        arg1: ::core::ffi::c_uchar,
    );
    pub fn readDataBus(
        state: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_uchar;
    pub fn readIR(state: *mut ::core::ffi::c_void) -> ::core::ffi::c_uchar;
    pub static mut memory: [::core::ffi::c_uchar; 65536usize];
    pub static mut cycle: ::core::ffi::c_uint;
    pub static mut transistors: ::core::ffi::c_uint;
}
